### ISSUE TITLE
HTC One

### ISSUE THREAD

**Issue by robneu** [robneu/firefox-mobile-device-presets#12]
## Firefox:

![screen shot 2015-03-20 at 6 36 17 pm](https://cloud.githubusercontent.com/assets/3010133/6762977/14aa0fb4-cf31-11e4-91c8-19e46af1f962.png)

**Comment by mzak** [comment]
## HTC One M8:

![2015-03-21 00 35 19](https://cloud.githubusercontent.com/assets/3010133/6762969/e8eb9c76-cf30-11e4-9014-c14d0f2397ac.png)

**Comment by robneu** [comment]
:+1: Looks good! I'll leave this one open for now to see if any of the other versions of the HTC One have issues, but I think at least the M8 can be considered verified.

**Comment by hansswolfs** [comment]
I have the HTC One m7 here... not my main phone but I'm charging it and will post screenie here from your site too Rob.

**Comment by hansswolfs** [comment]
HTC One m7 : 
![screenshot_2015-03-23-19-32-59](https://cloud.githubusercontent.com/assets/7773447/6787624/4c5c798c-d194-11e4-97b8-b76d06ff868d.png)

Looks good as well so guess we can have HTC One verified.
