### ISSUE TITLE
Microsoft Lumia

### ISSUE THREAD

**Issue by robneu** [robneu/firefox-mobile-device-presets#17]

**Comment by hansswolfs** [comment]
Firefox MS Lumia preset : 
![hansswolfs be - firefox ms lumia preset](https://cloud.githubusercontent.com/assets/7773447/6788056/50b268d6-d197-11e4-8935-e67c1bb498d5.png)

**Comment by hansswolfs** [comment]
Lumia 930 : 
![hansswolfs be lumia 930](https://cloud.githubusercontent.com/assets/7773447/6788115/bc87986a-d197-11e4-85f2-2cdf6516c818.png)

**Comment by hansswolfs** [comment]
another one to leave open for other Lumia devices as this preset should prove to be very broad
