### ISSUE TITLE
Apple iPad

### ISSUE THREAD

**Issue by robneu** [robneu/firefox-mobile-device-presets#26]
This device preset is made up of quite a few different presets, so we'll need to test as many of them as possible before it can be considered verified.
## Firefox

![screen shot 2015-03-20 at 19 58 28](https://cloud.githubusercontent.com/assets/2184093/6763055/920f85ec-cf3b-11e4-8ef3-94bbc9a849b4.png)

**Comment by mzak** [comment]
## iPad Air 2:

![2015-03-20 18 48 38](https://cloud.githubusercontent.com/assets/3010133/6763032/7ae522f4-cf32-11e4-98d7-793304b99079.png)
