### ISSUE TITLE
Google Nexus 7 v2

### ISSUE THREAD

**Issue by robneu** [robneu/firefox-mobile-device-presets#29]

**Comment by hansswolfs** [comment]
Testing the Nexus 7 2013...
Seeing some differences but I'm not sure if that's due to the Share over LAN function from Desktopserver or the preset.

The background of my local website doesn't show when I view the site on my Nexus 7 but it does show in the preset from Firefox.

**Comment by hansswolfs** [comment]
Guess I'll just use live websites instead of local development sites.

**Comment by hansswolfs** [comment]
![schermafbeelding 2015-03-22 om 11 18 49](https://cloud.githubusercontent.com/assets/7773447/6768942/5d16c238-d085-11e4-8474-57cbbcbb5209.png) <-- desktop

**Comment by hansswolfs** [comment]
![screenshot_2015-03-22-11-18-38](https://cloud.githubusercontent.com/assets/7773447/6768956/bf744c0c-d085-11e4-8343-1fe8e125d908.png) 
Nexus 7 2013 screenshot all looking nice!

**Comment by robneu** [comment]
Looks good! Thanks for the test.
