### ISSUE TITLE
Google Nexus 7 v1

### ISSUE THREAD

**Issue by robneu** [robneu/firefox-mobile-device-presets#30]
## Firefox:

![screen shot 2015-03-20 at 6 58 52 pm](https://cloud.githubusercontent.com/assets/3010133/6763059/4079c826-cf33-11e4-8a8c-1038dc3bd1bb.png)

**Comment by mzak** [comment]
## Nexus 7 v1:

![2015-03-21 01 08 46](https://cloud.githubusercontent.com/assets/3010133/6763113/aba966b4-cf34-11e4-9e9d-467a0785a182.png)

**Comment by robneu** [comment]
Looks good! I think we can call this verified, although the browser chrome does take up quite a lot of space. Thanks for the help.
