### ISSUE TITLE
Microsoft Surface Pro

### ISSUE THREAD

**Issue by robneu** [robneu/firefox-mobile-device-presets#37]

**Comment by hansswolfs** [comment]
Firefox preset for Surface Pro : 
![hansswolfs be - firefox surface pro preset](https://cloud.githubusercontent.com/assets/7773447/6787911/280a4b2a-d196-11e4-8d80-36a63ecba840.png)

**Comment by hansswolfs** [comment]
Screenshot from Surface Pro 3 : 
![hansswolfs be surface pro 3](https://cloud.githubusercontent.com/assets/7773447/6787962/95cb7198-d196-11e4-858d-9aecc0e0b1d0.png)

**Comment by hansswolfs** [comment]
Looking verey good as well but suppose we can leave this one open for someone with a SP1 or SP2?

**Comment by robneu** [comment]
:+1: Sounds good to me.
