### ISSUE TITLE
Apple iPhone 3 & 4

### ISSUE THREAD

**Issue by robneu** [robneu/firefox-mobile-device-presets#4]
These devices need to be tested for accuracy.

**Comment by clayteller** [comment]
Looks accurate to me. 
![screen shot 2015-03-25 at 11 34 56 am](https://cloud.githubusercontent.com/assets/216371/6832405/7a66ef7e-d2e3-11e4-8d28-869f43b30f4b.png)
![2015-03-25 11 30 10](https://cloud.githubusercontent.com/assets/216371/6832415/8b7b67ea-d2e3-11e4-98a4-f9fd8bc4dc5d.png)
